
source 'git@github.com:funkyHS/FunkyFMSpecs.git'  #私有的远程代码仓库
source 'https://github.com/CocoaPods/Specs.git'  #官方仓库的地址


use_frameworks!

target 'FunkyFMHomeRecommend_Example' do
  pod 'FunkyFMHomeRecommend', :path => '../'

  target 'FunkyFMHomeRecommend_Tests' do
    inherit! :search_paths

    
  end
end
